### ISSUE TITLE
man fix AAA BBB

### ISSUE THREAD

**Issue by L89David** [koerbackup23934056975/BD-Plugins#1]
░░░░░░░░░░░░░░░░▄▄▄███████▄▄░░░░░░░░░░░░
░░░░░░░░░░░░░░▄███████████████▄░░░░░░░░░
░░░░░░░░░░░░░█▀▀▀▄░░░░█████▀▀███▄░░░░░░░
░░░░░░░░░░░░█░░▄░░█▄▄█░░░░▀▄▄█████░░░░░░
░░░░░░░░░▄▀▀▀▄▄▀▀▀▀▀▀▄░░▀░░█▀▀▀░▀██░░░░░
░░░░░░░▄▀░░░░░█░░░░░░▀▄▄▄▄█░░░░░░░▀▄░░░░
░░░░░░▄▀░░░░░▄█▀▄▄▄▄░░░░░▄░░░░░░░░░█░░░░
░░░░░░█░░░░░▄█▀▄▄▄▄▄▄▄▄▄▀▀░░░░░░░░░▀▄░░░
░░░░░█░░░░░░▀█▄░░░░░░░░░░░░░░░░░░░░░█░░░
░░░░░█░░░░░░░░▀▄░░░░░░░░░░░░░░░░░░░░█░░░
░░░░░█░░░░░░░░▄█░░░░░░░░░░░░░░░░░░░░█░░░
░░░░░█░░░░░░▄▀░░░░░░░░▀▄░░░░░░░░░░░░█░░░
░░░░░█░░░░░░▀▄░░░▄░░░░░█░░░░░░░░░░░░█░░░
░░░░░█░░░░░░░░▀▀▀▀▀█▄▄▀░░░░░░░░░░░░░█░░░
░░░░░█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▄██░░
░░░░░█▄░░░░░░░░░░░░░░░░░░░░░░░░░░▄▀▀▄▀▄▄
░░░░▄█▀▄░░░░░░░░░░░░░░░░░░░░░░▄▄▀░░▄▀░░░
░▄░▀░░█░▀▄▄░░░░░░░░░░░░░░░▄▄▄▀░░░▄▀░░░░░
▀░░░░░░▀▄░░▀▄░░░░░░░░▄▄▄▀▀░░░░▄▀▀░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░░░░░░░░░░░░██░░██░░██████░░░░░░░░░░░░░
░░░░░░░░░░░░░██░░██░░██░░██░░░░░░░░░░░░░
░░░░░░░░░░░░░██████░░██░░██░░░░░░░░░░░░░
░░░░░░░░░░░░░██░░██░░██░░██░░░░░░░░░░░░░
░░░░░░░░░░░░░██░░██░░██████░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

**Comment by koerbackup23934056975** [comment]
man

**Comment by koerbackup23934056975** [comment]
will do

**Comment by L89David** [comment]
opg

**Comment by L89David** [comment]
pog

**Comment by koerbackup23934056975** [comment]
60% done
